# Generated by Django 4.2.1 on 2023-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
