# Generated by Django 4.2.1 on 2023-05-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0003_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contra2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
