# Generated by Django 4.2.1 on 2023-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0007_remove_rol_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('E', 'Estandar'), ('V', 'Vendedor'), ('B', 'Bodeguero')], default='E', max_length=1),
        ),
    ]
