# Generated by Django 4.2.1 on 2023-05-27 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guitar', '0009_delete_user_delete_usuario_rol_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='Trabajador',
        ),
    ]
